// <auto-generated />
namespace LabThree.Migrations.LabThreeMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PInitalCreate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PInitalCreate2));
        
        string IMigrationMetadata.Id
        {
            get { return "201709260223281_PInitalCreate2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
